version: '3'
services:

  #PHP App
  app:
    build:
      context: .
      dockerfile: config/dockerfile
    image: php:7.4-fpm-alpine
    container_name: php_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: prod
    working_dir: /var/www/crm
    volumes:
      - ./code/:/var/www/crm
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - labnet

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "4301:80"
    volumes:
      - ./code/:/var/www/crm
      - ./config/conf.d/:/etc/nginx/conf.d/
    networks:
      - labnet

#Docker Networks
networks:
  labnet: 
    external:
      name: labnet
